name: Pull, Retag, Compare, and Push IOS-MCN-CORE Docker Images

on:
  workflow_dispatch:
    inputs:
      udr_source_version:
        description: 'Source Version for UDR'
        required: true
        default: 'release-0.2.2'
      udr_target_version:
        description: 'Target Version for UDR'
        required: true
        default: 'release-0.2.2'
      nssf_source_version:
        description: 'Source Version for NSSF'
        required: true
        default: 'release-0.2.1'
      nssf_target_version:
        description: 'Target Version for NSSF'
        required: true
        default: 'release-0.2.1'
      webui_source_version:
        description: 'Source Version for WEBUI'
        required: true
        default: 'release-0.2.2'
      webui_target_version:
        description: 'Target Version for WEBUI'
        required: true
        default: 'release-0.2.2'
      metricfunc_source_version:
        description: 'Source Version for METRICFUNC'
        required: true
        default: 'release-0.2.1'
      metricfunc_target_version:
        description: 'Target Version for METRICFUNC'
        required: true
        default: 'release-0.2.1'
      ausf_source_version:
        description: 'Source Version for AUSF'
        required: true
        default: 'release-0.2.1'
      ausf_target_version:
        description: 'Target Version for AUSF'
        required: true
        default: 'release-0.2.1'

jobs:
  pull_retag_compare_push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Scout (if not already installed)
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
      - name: Pull, Retag, Compare, and Push Docker Images
        run: |
          # Define associative arrays for source and target versions
          declare -A SOURCE_VERSIONS=(
            ["5gc-udr"]="${{ github.event.inputs.udr_source_version }}"
            ["5gc-nssf"]="${{ github.event.inputs.nssf_source_version }}"
            ["5gc-webui"]="${{ github.event.inputs.webui_source_version }}"
            ["metricfunc"]="${{ github.event.inputs.metricfunc_source_version }}"
            ["5gc-ausf"]="${{ github.event.inputs.ausf_source_version }}"
          )
          
          declare -A TARGET_VERSIONS=(
            ["5gc-udr"]="${{ github.event.inputs.udr_target_version }}"
            ["5gc-nssf"]="${{ github.event.inputs.nssf_target_version }}"
            ["5gc-webui"]="${{ github.event.inputs.webui_target_version }}"
            ["metricfunc"]="${{ github.event.inputs.metricfunc_target_version }}"
            ["5gc-ausf"]="${{ github.event.inputs.ausf_target_version }}"
          )
          
          for PACKAGE in "${!SOURCE_VERSIONS[@]}"; do
            SOURCE_VERSION=${SOURCE_VERSIONS[$PACKAGE]}
            TARGET_VERSION=${TARGET_VERSIONS[$PACKAGE]}
            
            SOURCE_IMAGE="ghcr.io/ios-mcn-core/${PACKAGE}:${SOURCE_VERSION}"
            TARGET_IMAGE="ghcr.io/ios-mcn/${PACKAGE}:${TARGET_VERSION}"
            
            echo "Processing ${PACKAGE}..."
            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            
            echo "Retagging ${SOURCE_IMAGE} as ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            
            echo "Comparing ${SOURCE_IMAGE} and ${TARGET_IMAGE}..."
            docker scout compare ${SOURCE_IMAGE} --to ${TARGET_IMAGE}
            
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
            
            echo "Completed processing ${PACKAGE}"
          done
