name: Pull, Retag, and Push Images from ios-mcn-core

on:
  workflow_dispatch:
    inputs:
      udr_version:
        description: 'Version tag for UDR'
        required: true
        default: 'release-0.0.10'
      nssf_version:
        description: 'Version tag for NSSF'
        required: true
        default: 'release-0.0.6'
      webui_version:
        description: 'Version tag for WEBUI'
        required: true
        default: 'release-0.0.4'
      metricfunc_version:
        description: 'Version tag for metricfunc'
        required: true
        default: 'release-0.0.5'
      ausf_version:
        description: 'Version tag for ausf'
        required: true
        default: 'release-0.0.4'
     

jobs:
  pull_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

     
      - name: Pull, Retag, and Push all Images from ios-mcn-core
        run: |
          
          declare -A CORE_PACKAGES
          CORE_PACKAGES=(
            ["5gc-udr"]="${{ github.event.inputs.udr_version }}"
            ["5gc-nssf"]="${{ github.event.inputs.nssf_version }}"
            ["5gc-webui"]="${{ github.event.inputs.webui_version }}"
            ["metricfunc"]="${{ github.event.inputs.metricfunc_version }}"
            ["5gc-ausf"]="${{ github.event.inputs.ausf_version }}"
            
          )
          
          
          for PACKAGE in "${!CORE_PACKAGES[@]}"; do
            VERSION=${CORE_PACKAGES[$PACKAGE]}
            SOURCE_IMAGE="ghcr.io/ios-mcn-core/${PACKAGE}:${VERSION}"
            TARGET_IMAGE="ghcr.io/ios-mcn/${PACKAGE}:${VERSION}"  
            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            echo "Retagging ${SOURCE_IMAGE} to ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
          done
