name: Pull, Retag, and Push Images from ios-mcn-core

on:
  workflow_dispatch:
    inputs:
      simapp_version:
        description: 'Version tag for simapp'
        required: true
        default: 'release-0.0.3'
      upf-epc-bess_version:
        description: 'Version tag for upf-epc-bess'
        required: true
        default: 'release-haswell-0.0.4'
      upf-epc-pfcpiface_version:
        description: 'Version tag for upf-epc-pfcpiface'
        required: true
        default: 'release-haswell-0.0.4'
     
     

jobs:
  pull_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

     
      - name: Pull, Retag, and Push all Images from ios-mcn-core
        run: |
          
          declare -A CORE_PACKAGES
          CORE_PACKAGES=(
            ["simapp"]="${{ github.event.inputs.simapp_version }}"
            ["upf-epc-bess"]="${{ github.event.inputs.upf-epc-bess_version }}"
            ["upf-epc-pfcpiface"]="${{ github.event.inputs.upf-epc-pfcpiface_version }}"
            
            
          )
          
          
          for PACKAGE in "${!CORE_PACKAGES[@]}"; do
            VERSION=${CORE_PACKAGES[$PACKAGE]}
            SOURCE_IMAGE="ghcr.io/ios-mcn-core/${PACKAGE}:${VERSION}"
            TARGET_IMAGE="ghcr.io/ios-mcn/${PACKAGE}:${VERSION}"  
            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            echo "Retagging ${SOURCE_IMAGE} to ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
          done
