name: Pull, Retag, Compare, and Push IOS-MCN-SMO Docker Images

on:
  workflow_dispatch:
    inputs:
      nonrtric-plt-dmaapadapter_source_version:
        description: 'Source Version for nonrtric-plt-dmaapadapter'
        required: true
        default: '1.4.1'
      nonrtric-plt-dmaapadapter_target_version:
        description: 'Target Version for nonrtric-plt-dmaapadapter'
        required: true
        default: '1.4.1'
      # ves-collector_source_version:
      #   description: 'Source Version for ves-collector'
      #   required: true
      #   default: '1.12.4'
      # ves-collector_target_version:
      #   description: 'Target Version for ves-collector'
      #   required: true
      #   default: '1.12.4'
      # pm-file-converter_source_version:
      #   description: 'Source Version for pm-file-converter'
      #   required: true
      #   default: '1.2.1'
      # pm-file-converter_target_version:
      #   description: 'Target Version for pm-file-converter'
      #   required: true
      #   default: '1.2.1'
      # nonrtric-gateway_source_version:
      #   description: 'Source Version for nonrtric-gateway'
      #   required: true
      #   default: '1.2.1'
      # nonrtric-gateway_target_version:
      #   description: 'Target Version for nonrtric-gateway'
      #   required: true
      #   default: '1.2.1'
      # nonrtric-controlpanel_source_version:
      #   description: 'Source Version for nonrtric-controlpanel'
      #   required: true
      #   default: '2.5.1'
      # nonrtric-controlpanel_target_version:
      #   description: 'Target Version for nonrtric-controlpanel'
      #   required: true
      #   default: '2.5.1'

jobs:
  pull_retag_compare_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Scout (if not already installed)
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
      - name: Pull, Retag, Compare, and Push Docker Images
        run: |
          # Define associative arrays for source and target versions
          declare -A SOURCE_VERSIONS=(
            ["nonrtric-plt-dmaapadapter"]="${{ github.event.inputs.nonrtric-plt-dmaapadapter_source_version }}"
            # ["ves-collector"]="${{ github.event.inputs.ves-collector_source_version }}"
            # ["pm-file-converter"]="${{ github.event.inputs.pm-file-converter_source_version }}"
            # ["nonrtric-gateway"]="${{ github.event.inputs.nonrtric-gateway_source_version }}"
            # ["nonrtric-controlpanel"]="${{ github.event.inputs.nonrtric-controlpanel_source_version }}"
          )
          
          declare -A TARGET_VERSIONS=(
            ["nonrtric-plt-dmaapadapter"]="${{ github.event.inputs.nonrtric-plt-dmaapadapter_target_version }}"
            # ["ves-collector"]="${{ github.event.inputs.ves-collector_target_version }}"
            # ["pm-file-converter"]="${{ github.event.inputs.pm-file-converter_target_version }}"
            # ["nonrtric-gateway"]="${{ github.event.inputs.nonrtric-gateway_target_version }}"
            # ["nonrtric-controlpanel"]="${{ github.event.inputs.nonrtric-controlpanel_target_version }}"
          )
          
          for PACKAGE in "${!SOURCE_VERSIONS[@]}"; do
            SOURCE_VERSION=${SOURCE_VERSIONS[$PACKAGE]}
            TARGET_VERSION=${TARGET_VERSIONS[$PACKAGE]}
            
            SOURCE_IMAGE="ghcr.io/ios-mcn-smo/${PACKAGE}:${SOURCE_VERSION}"
            TARGET_IMAGE="ghcr.io/ios-mcn/${PACKAGE}:${TARGET_VERSION}"
            
            echo "Processing ${PACKAGE}..."
            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            
            echo "Retagging ${SOURCE_IMAGE} as ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            
            echo "Comparing ${SOURCE_IMAGE} and ${TARGET_IMAGE}..."
            docker scout compare ${SOURCE_IMAGE} --to ${TARGET_IMAGE}
            
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
            
            echo "Completed processing ${PACKAGE}"
          done
