name: Pull, Retag, Compare, and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      simapp_source_version:
        description: 'Source Version for simapp (e.g., release-0.0.10)'
        required: true
        default: 'release-0.0.3'
      simapp_target_version:
        description: 'Target Version for simapp (e.g., v1.0.0)'
        required: true
        default: 'release-0.0.3'
      upf-epc-bess_source_version:
        description: 'Source Version for upf-epc-bess'
        required: true
        default: 'release-ivybridge-0.0.4'
      upf-epc-bess_target_version:
        description: 'Target Version for upf-epc-bess'
        required: true
        default: 'release-ivybridge-0.0.4'
      upf-epc-pfcpiface_source_version:
        description: 'Source Version for  upf-epc-pfcpiface'
        required: true
        default: 'release-ivybridge-0.0.4'
      upf-epc-pfcpiface_target_version:
        description: 'Target Version for  upf-epc-pfcpiface'
        required: true
        default: 'release-ivybridge-0.0.4'
      bess_build_source_version:
        description: 'Source Version for bess-build'
        required: true
        default: '240926'
      bess_build_target_version:
        description: 'Target Version for bess-build'
        required: true
        default: '240926'
      

jobs:
  pull_retag_compare_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Scout (if not already installed)
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
      - name: Pull, Retag, Compare, and Push Docker Images
        run: |
          # Define associative arrays for source and target versions
          declare -A SOURCE_VERSIONS=(
            ["simapp"]="${{ github.event.inputs.simapp_source_version }}"
            ["upf-epc-bess"]="${{ github.event.inputs.upf-epc-bess_source_version }}"
            ["upf-epc-pfcpiface"]="${{ github.event.inputs.upf-epc-pfcpiface_source_version }}"
            ["bess_build"]="${{ github.event.inputs.bess_build_source_version }}"
            
          )
          
          declare -A TARGET_VERSIONS=(
            ["simapp"]="${{ github.event.inputs.simapp_target_version }}"
            ["upf-epc-bess"]="${{ github.event.inputs.upf-epc-bess_target_version }}"
            ["upf-epc-pfcpiface"]="${{ github.event.inputs.upf-epc-pfcpiface_target_version }}"
            ["bess_build"]="${{ github.event.inputs.bess_build_target_version }}"
            
          )
          
          for PACKAGE in "${!SOURCE_VERSIONS[@]}"; do
            SOURCE_VERSION=${SOURCE_VERSIONS[$PACKAGE]}
            TARGET_VERSION=${TARGET_VERSIONS[$PACKAGE]}
            
            SOURCE_IMAGE="ghcr.io/ios-mcn-core/${PACKAGE}:${SOURCE_VERSION}"
            TARGET_IMAGE="ghcr.io/test-ios-mcn-caze/${PACKAGE}:${TARGET_VERSION}"
            
            echo "Processing ${PACKAGE}..."
            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            
            echo "Retagging ${SOURCE_IMAGE} as ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            
            echo "Comparing ${SOURCE_IMAGE} and ${TARGET_IMAGE}..."
            docker scout compare ${SOURCE_IMAGE} --to ${TARGET_IMAGE}
            
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
            
            echo "Completed processing ${PACKAGE}"
          done
