name: Pull, Retag, Compare, and Push IOS-MCN-SMO Docker Images

on:
  workflow_dispatch:
    inputs:
      sa-rapp_source_version:
        description: 'Source Version for sa-rapp'
        required: true
        default: '1.0'
      sa-rapp_target_version:
        description: 'Target Version for sa-rapp'
        required: true
        default: '1.0'
      oru-rapp_source_version:
        description: 'Source Version for oru-rapp'
        required: true
        default: '1.0'
      oru-rapp_target_version:
        description: 'Target Version for oru-rapp'
        required: true
        default: '1.0'
      ric-plt-submgr_source_version:
        description: 'Source Version for ric-plt-submgr'
        required: true
        default: '0.10.1'
      ric-plt-submgr_target_version:
        description: 'Target Version for ric-plt-submgr'
        required: true
        default: '0.10.1'
      

jobs:
  pull_retag_compare_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Scout (if not already installed)
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

      - name: Pull, Retag, Compare, and Push Docker Images
        run: |
          # Define associative arrays for source and target versions
          declare -A SOURCE_VERSIONS=(
            ["sa-rapp"]="${{ github.event.inputs.sa-rapp_source_version }}"
            ["oru-rapp"]="${{ github.event.inputs.oru-rapp_source_version }}"
            ["ric-plt-submgr"]="${{ github.event.inputs.ric-plt-submgr_source_version }}"
            
          )
          
          declare -A TARGET_VERSIONS=(
            ["sa-rapp"]="${{ github.event.inputs.sa-rapp_target_version }}"
            ["oru-rapp"]="${{ github.event.inputs.oru-rapp_target_version }}"
            ["ric-plt-submgr"]="${{ github.event.inputs.ric-plt-submgr_target_version }}"
            
          )
          
          for PACKAGE in "${!SOURCE_VERSIONS[@]}"; do
            SOURCE_VERSION=${SOURCE_VERSIONS[$PACKAGE]}
            TARGET_VERSION=${TARGET_VERSIONS[$PACKAGE]}
            
            SOURCE_IMAGE="ghcr.io/ios-mcn-smo/${PACKAGE}:${SOURCE_VERSION}"
            TARGET_IMAGE="ghcr.io/ios-mcn/${PACKAGE}:${TARGET_VERSION}"
            
            echo "Processing ${PACKAGE}..."
            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            
            echo "Retagging ${SOURCE_IMAGE} as ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            
            echo "Comparing ${SOURCE_IMAGE} and ${TARGET_IMAGE}..."
            docker scout compare ${SOURCE_IMAGE} --to ${TARGET_IMAGE}
            
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
            
            echo "Completed processing ${PACKAGE}"
          done
