name: Pull, Retag, and Push Docker Images with Different Versions

on:
  workflow_dispatch:
    inputs:
      amf_version:
        description: 'Version tag for AMF (e.g., v0.0.10)'
        required: true
        default: 'v0.0.10'
      smf_version:
        description: 'Version tag for SMF (e.g., v0.0.6)'
        required: true
        default: 'v0.0.6'
      pcf_version:
        description: 'Version tag for PCF (e.g., v0.0.4)'
        required: true
        default: 'v0.0.4'
      nrf_version:
        description: 'Version tag for NRF (e.g., v0.0.5)'
        required: true
        default: 'v0.0.5'
      udm_version:
        description: 'Version tag for UDM (e.g., v0.0.4)'
        required: true
        default: 'v0.0.4'
      # Add other versions for each package
      smf_version:
        description: 'Version tag for SMF (e.g., v0.0.6)'
        required: true
        default: 'v0.0.6'
      nonrtric_plt_a1_version:
        description: 'Version tag for nonrtric-plt-a1policymanagementservice (e.g., v2.8.1)'
        required: true
        default: 'v2.8.1'

jobs:
  pull_and_push_images:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository (if needed)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 1: Pull, Retag, and Push all Images from ios-mcn-core
      - name: Pull, Retag, and Push all Images from ios-mcn-core
        run: |
          # Define the list of packages and their respective versions for ios-mcn-core
          declare -A CORE_PACKAGES
          CORE_PACKAGES=(
            ["amf"]="${{ github.event.inputs.amf_version }}"
            ["smf"]="${{ github.event.inputs.smf_version }}"
            ["pcf"]="${{ github.event.inputs.pcf_version }}"
            ["nrf"]="${{ github.event.inputs.nrf_version }}"
            ["udm"]="${{ github.event.inputs.udm_version }}"
            ["udr"]="v0.0.4"
            ["nssf"]="v0.0.4"
            ["webconsole"]="v0.0.4"
            ["metricfunction"]="v0.0.4"
            ["ausf"]="v0.0.4"
          )

          # Loop through each package and perform pull, retag, and push
          for PACKAGE in "${!CORE_PACKAGES[@]}"; do
            VERSION=${CORE_PACKAGES[$PACKAGE]}
            SOURCE_IMAGE="ghcr.io/ios-mcn-core/${PACKAGE}:${VERSION}"
            TARGET_IMAGE="ghcr.io/Test-IOS-MCN-CAZE/IOS_MCN/${PACKAGE}:${VERSION}-updated"

            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            echo "Retagging ${SOURCE_IMAGE} to ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
          done

      # Step 2: Pull, Retag, and Push all Images from ios-mcn-smo
      - name: Pull, Retag, and Push all Images from ios-mcn-smo
        run: |
          # Define the list of packages and their respective versions for ios-mcn-smo
          declare -A SMO_PACKAGES
          SMO_PACKAGES=(
            ["nonrtric-plt-a1policymanagementservice"]="${{ github.event.inputs.nonrtric_plt_a1_version }}"
            ["nonrtric-plt-rappcatalogue"]="v2.8.1"
            ["nonrtric-plt-informationcoordinatorservice"]="v0.0.5"
            ["nonrtric-plt-pmproducer"]="v0.0.5"
            ["nonrtric-plt-pmlog"]="v0.0.5"
            ["nonrtric-plt-dmaapadapter"]="v2.8.1"
            ["ves-collector"]="v0.0.4"
            ["pm-file-converter"]="v0.0.4"
            ["nonrtric-gateway"]="v0.0.4"
            ["nonrtric-controlpanel"]="v0.0.4"
            ["nonrtric-plt-auth-token-fetch"]="v0.0.4"
            ["sdnc-web-image"]="v0.0.4"
            ["sdnc-image"]="v0.0.4"
          )

          # Loop through each package and perform pull, retag, and push
          for PACKAGE in "${!SMO_PACKAGES[@]}"; do
            VERSION=${SMO_PACKAGES[$PACKAGE]}
            SOURCE_IMAGE="ghcr.io/ios-mcn-smo/${PACKAGE}:${VERSION}"
            TARGET_IMAGE="ghcr.io/Test-IOS-MCN-CAZE/IOS_MCN/${PACKAGE}:${VERSION}-updated"

            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            echo "Retagging ${SOURCE_IMAGE} to ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
          done
