name: Pull, Retag, and Push Images from ios-mcn-ran

on:
  workflow_dispatch:
    inputs:
      # ran-base-dist_version:
      #   description: 'Version tag for ran-base-dist (e.g., release-0.0.10)'
      #   required: true
      #   default: 'v0.1.4.rc4'
      # ios-mcn-cuup-dist_version:
      #   description: 'Version tag for ios-mcn-cuup-dist (e.g., release-0.0.6)'
      #   required: true
      #   default: 'v0.1.4.rc4'
      ran-build-dist_version:
        description: 'Version tag for ran-build-dist (e.g., release-0.0.4)'
        required: true
        default: 'v0.1.4.rc4'
      ios-mcn-gnb-dist_version:
        description: 'Version tag for ios-mcn-gnb-dist (e.g., release-0.0.5)'
        required: true
        default: 'v0.1.4.rc4'
      ran-base-uni_version:
        description: 'Version tag for ran-base-uni (e.g., release-0.0.4)'
        required: true
        default: 'v0.1.4.rc4'
     

jobs:
  pull_and_push_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

     
      - name: Pull, Retag, and Push all Images from ios-mcn-core
        run: |
          
          declare -A RAN_PACKAGES
          RAN_PACKAGES=(
            # ["ran-base-dist"]="${{ github.event.inputs.ran-base-dist_version }}"
            # ["ios-mcn-cuup-dist"]="${{ github.event.inputs.ios-mcn-cuup-dist_version }}"
            ["ran-build-dist"]="${{ github.event.inputs.ran-build-dist_version }}"
            ["ios-mcn-gnb-dist"]="${{ github.event.inputs.ios-mcn-gnb-dist_version }}"
            ["ran-base-uni"]="${{ github.event.inputs.ran-base-uni_version }}"
            
          )
          
          
          for PACKAGE in "${!RAN_PACKAGES[@]}"; do
            VERSION=${RAN_PACKAGES[$PACKAGE]}
            SOURCE_IMAGE="ghcr.io/ios-mcn-ran/${PACKAGE}:${VERSION}"
            TARGET_IMAGE="ghcr.io/ios-mcn/${PACKAGE}:${VERSION}"  
            echo "Pulling ${SOURCE_IMAGE}..."
            docker pull ${SOURCE_IMAGE}
            echo "Retagging ${SOURCE_IMAGE} to ${TARGET_IMAGE}..."
            docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
            echo "Pushing ${TARGET_IMAGE}..."
            docker push ${TARGET_IMAGE}
          done
