name: Transfer Maven Package from Be-with-DevOps

on:
  workflow_dispatch:
    inputs:
      artifact_id:
        description: 'Artifact ID to transfer'
        required: true
        default: 'odl-netconf-model-rfc6241'
      version:
        description: 'Version to transfer'
        required: true
        default: '6.0.6'
      packaging:
        description: 'Package type (jar, war, etc.)'
        required: true
        default: 'jar'

jobs:
  transfer-maven-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout nivedita-releases repo
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << 'EOF'
        <settings>
          <servers>
            <server>
              <id>github-source</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.SOURCE_GITHUB_TOKEN}</password>
            </server>
            <server>
              <id>github-nivedita</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.GITHUB_TOKEN}</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>github</id>
              <repositories>
                <repository>
                  <id>github-source</id>
                  <url>https://maven.pkg.github.com/Be-with-DevOps/demo-netconf-test.2</url>
                  <releases><enabled>true</enabled></releases>
                  <snapshots><enabled>true</enabled></snapshots>
                </repository>
                <repository>
                  <id>central</id>
                  <url>https://repo1.maven.apache.org/maven2</url>
                  <releases><enabled>true</enabled></releases>
                  <snapshots><enabled>false</enabled></snapshots>
                </repository>
              </repositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>github</activeProfile>
          </activeProfiles>
        </settings>
        EOF
      env:
        SOURCE_GITHUB_TOKEN: ${{ secrets.SOURCE_GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download package from Be-with-DevOps
      run: |
        mkdir -p temp
        mvn dependency:copy \
          -Dartifact=org.opendaylight.netconf:${{ github.event.inputs.artifact_id }}:${{ github.event.inputs.version }}:${{ github.event.inputs.packaging }} \
          -DoutputDirectory=./temp/ \
          -Dmdep.stripVersion=false
      env:
        SOURCE_GITHUB_TOKEN: ${{ secrets.SOURCE_GITHUB_TOKEN }}
    
    - name: Verify downloaded file
      run: |
        ls -la temp/
        FILE_PATH="./temp/${{ github.event.inputs.artifact_id }}-${{ github.event.inputs.version }}.${{ github.event.inputs.packaging }}"
        if [ ! -f "$FILE_PATH" ]; then
          echo "Error: Downloaded file not found at $FILE_PATH"
          exit 1
        fi
        echo "File successfully downloaded: $FILE_PATH"
    
    - name: Deploy to nivedita-releases
      run: |
        mvn deploy:deploy-file \
          -DgroupId=com.github.nivedita-releases \
          -DartifactId=${{ github.event.inputs.artifact_id }} \
          -Dversion=${{ github.event.inputs.version }} \
          -Dpackaging=${{ github.event.inputs.packaging }} \
          -Dfile=./temp/${{ github.event.inputs.artifact_id }}-${{ github.event.inputs.version }}.${{ github.event.inputs.packaging }} \
          -DrepositoryId=github-nivedita \
          -Durl=https://maven.pkg.github.com/nivedita-releases/maven-packages \
          -DgeneratePom=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Cleanup
      run: rm -rf temp
