name: Copy Maven Package
 
on:
  workflow_dispatch: # Trigger manually from GitHub UI
    inputs:
      version:
        description: "Package version to copy"
        required: true
        default: "0.0.1"
 
jobs:
  copy-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (empty repo, just for workspace)
        uses: actions/checkout@v4
 
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - name: Download artifacts from old org
        run: |
          BASE_URL="https://maven.pkg.github.com"
          PACKAGE_GROUP="org.iosmcn"
          PACKAGE_ARTIFACT="pcscf"
          PACKAGE_VERSION="${{ github.event.inputs.version }}"
 
          mkdir artifacts && cd artifacts
          echo "📥 Downloading $PACKAGE_ARTIFACT:$PACKAGE_VERSION from ios-mcn-ims..."
          curl -u ${{ secrets.OLD_ORG_USERNAME }}:${{ secrets.OLD_ORG_TOKEN }} \
            -O "$BASE_URL/ios-mcn-ims/$PACKAGE_GROUP/$PACKAGE_ARTIFACT/$PACKAGE_VERSION/$PACKAGE_ARTIFACT-$PACKAGE_VERSION.jar"
          curl -u ${{ secrets.OLD_ORG_USERNAME }}:${{ secrets.OLD_ORG_TOKEN }} \
            -O "$BASE_URL/ios-mcn-ims/$PACKAGE_GROUP/$PACKAGE_ARTIFACT/$PACKAGE_VERSION/$PACKAGE_ARTIFACT-$PACKAGE_VERSION.pom"
 
      - name: Upload to new org
        run: |
          BASE_URL="https://maven.pkg.github.com"
          PACKAGE_GROUP="org.iosmcn"
          PACKAGE_ARTIFACT="pcscf"
          PACKAGE_VERSION="${{ github.event.inputs.version }}"
 
          echo "📤 Uploading to ios-mcn..."
          mvn deploy:deploy-file \
            -DgroupId="$PACKAGE_GROUP" \
            -DartifactId="$PACKAGE_ARTIFACT" \
            -Dversion="$PACKAGE_VERSION" \
            -Dpackaging=jar \
            -Dfile="artifacts/$PACKAGE_ARTIFACT-$PACKAGE_VERSION.jar" \
            -DpomFile="artifacts/$PACKAGE_ARTIFACT-$PACKAGE_VERSION.pom" \
            -DrepositoryId=github \
            -Durl="$BASE_URL/ios-mcn/$PACKAGE_ARTIFACT" \
            -DgeneratePom=false \
            -DretryFailedDeploymentCount=3 \
            -DuniqueVersion=false
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_ORG_TOKEN }}
